name: Duplicate Code Check

on:
  push:
    branches:
      - main

jobs:
  check-duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Duplicate Code Detection Tool
        uses: platisd/duplicate-code-detection-tool@master
